---
- hosts: ubuntu
  become: yes
  tasks:
  - name: Install necessary packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - python3-pip
      - python3-dev
      - virtualenv
      - nginx

  - name: Install Gunicorn with pip
    pip:
      name: gunicorn
      state: present

  - name: Create a directory for the app
    file:
      path: /var/www/flaskapp
      state: directory

  - name: Copy the Flask app to the servers
    copy:
      src: /home/ubuntu/flask-web-app
      dest: /var/www/flaskapp

  - name: Set up a virtual environment and install dependencies
    shell: |
      virtualenv venv
      source venv/bin/activate
      pip install -r requirements.txt
    args:
      chdir: /var/www/flaskapp

  - name: Configure Gunicorn systemd service
    template:
      src: /home/ubuntu/flask-web-app/templates/gunicorn.service.j2
      dest: /etc/systemd/system/gunicorn.service
      
  - name: Enable and start the Gunicorn service
    systemd:
      name: gunicorn
      enabled: yes
      state: started

  - name: Configure Nginx to proxy to Gunicorn
    template:
      src: nginx_flask.j2
      dest: /etc/nginx/sites-available/flaskapp
    notify:
      - restart nginx

  handlers:
  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
...
